default:
	just --list --unsorted

export-scenes:
	cargo run --example export-bevyhub-template

run:
	cargo run --example app -- scenes/my-base-scene.json scenes/my-beautiful-scene.json

pkg *args:
	cargo package --no-verify --allow-dirty {{args}}