[package]
name = "bevyhub_core"
version.workspace = true
edition.workspace = true
description.workspace = true
documentation.workspace = true
homepage.workspace = true
repository.workspace = true
license.workspace = true
keywords.workspace = true
categories.workspace = true


[dependencies]
forky.workspace = true
bevyhub_net.workspace = true
bevyhub_scene.workspace = true
bevy.workspace = true
log.workspace = true
anyhow.workspace = true
serde.workspace = true
extend.workspace = true

[dev-dependencies]
sweet.workspace = true
